### ISSUE TITLE
Could you publish Strong names nuget package

### ISSUE THREAD

**Issue by OliverMartini** [bytefish/TinyCsvParser#18]
Is there a chance that you could publish a strong named nuget package?

**Comment by bytefish** [comment]
Sure, but I won't be able to look into it this week.

**Comment by bytefish** [comment]
I have read an interesting discussion of Strong Naming Assemblies: 

* https://github.com/octokit/octokit.net/issues/405

It's not that easy for me. Is there any chance you could sign it yourself?

There is an example for self signing it in a discussion on Hangfire: 

* https://discuss.hangfire.io/t/please-add-strong-names-to-hangfire-assemblies/339/5

I would really appreciate if you self-sign the library, because the long discussion above is a little scary.

**Comment by bytefish** [comment]
Meanwhile I added Strong Naming of course. 👍 So in the end your request was totally valid.
