### ISSUE TITLE
Column is out of range

### ISSUE THREAD

**Issue by wernerbarnard** [bytefish/TinyCsvParser#24]
Hi,

I've got an issue with this row of data:

![image](https://user-images.githubusercontent.com/6905546/30581396-3d5d1018-9d20-11e7-88a2-ae50e83331c0.png)

Giving the error:

```
Invalid parsed CSV item: {item.RowIndex}/{item.Error.ColumnIndex} | '{item.Error.Value}' | {item.Error}
=
Invalid parsed CSV item: 981645/12 | 'Column 12 is Out Of Range' | CsvMappingError (ColumnIndex = 12, Value = Column 12 is Out Of Range)
```

Column index 12 is mapped to a string property.

My options:

```
new CsvParserOptions(false, '~', Environment.ProcessorCount * 4, true)
```

I'm thinking it might be the double quote that's unclosed in that line, as a text qualifier - how can I disable or change that behavior?

**Comment by bytefish** [comment]
That's an interesting one! Yes, probably that is a Bug in the ``Rfc4180Tokenizer``, which expects the Quotation to be correct. I will investigate this when I find the time.

As a fix for your data: It looks like "~" is not contained in your data, maybe that's why it was chosen as the delimiter. What will work for your data is switching to the ``StringSplitTokenizer``. The ``StringSplitTokenizer`` simply splits your data at the column delimiter and not cares about Quotes:

```csharp
CsvParserOptions csvParserOptions = new CsvParserOptions(true, string.Empty, new StringSplitTokenizer(new[] { '~' }, false));
```

Let me know, if this fixes your issue,

**Comment by wernerbarnard** [comment]
Hi @bytefish 

Works perfectly, thanks!

**Comment by bytefish** [comment]
Great! Thanks for the Feedback. ☺
