### ISSUE TITLE
Benchmark Page is confusing, possibly incorrect?

### ISSUE THREAD

**Issue by jtmueller** [bytefish/TinyCsvParser#27]
The [benchmark page](http://bytefish.github.io/TinyCsvParser/sections/benchmark.html) seems to be claiming that the LocalWeatherReadTest in the source code completes four passes in a total of 10.5 seconds.

The sample code in TinyCsvParserBenchmark() on that page appears to match the code in LocalWeatherReadTest().

I downloaded the exact same 201503hourly.txt file used in the example, 557 MB.

The test took 4 minutes to run, not 10.5 seconds. If I set the `degreeOfParallelismList` to only have one item in it, it still took a bit over 1 minute to run. Not 10.5 seconds.

Granted we're not running these tests on the same computer, but I have a really hard time believing your computer is 23 times faster than mine.

Can you shed any light on this? I'm unable to get results that are even slightly close to as fast as what's being claimed here. The only thing that's close is the SeqReadTest, which completes in 9-14 seconds for me, depending on what .NET Core runtime I use, but while that test uses the same input file, it doesn't use any TinyCsvParser code.

**Comment by bytefish** [comment]
When I wrote it, the default Tokenizer was the StringSplitTokenizer. This one is faster, because it simply splits at a given character. This made the speed possible. By now the default is the RFC4180Tokenizer, which requires more CPU cycles. I have to update the Benchmark or delete the page altogether. You can rerun the test with the StringSplitTokenizer, which will surely yield the mentioned results.

**Comment by jtmueller** [comment]
Thanks, that makes sense. I tried switching out the tokenizer for the StringSplitTokenizer, and it cut the processing time in half to 2 minutes for all four passes, or 43 seconds for a single non-parallel pass. It's still not 10.5 seconds, but it definitely does affect the performance.

**Comment by bytefish** [comment]
I will have access to a computer on saturday and then see, where performance could be improved and delete the benchmark page eventually.

**Comment by bytefish** [comment]
I have deleted the outdated Benchmark page in the README and GitHub Pages documentation. I will mark this ticket for performance improvements in upcoming versions.

**Comment by bytefish** [comment]
There has been a Benchmark of TinyCsvParser lately, which shows it can be made as fast as a ``string.Split`` in the given Benchmark. But the results are skewed, because I use Parallel LINQ while the other Parsers are sequential. I just wanted to let you know, I will update the page when I created fair Benchmarks.

**Comment by jtmueller** [comment]
I've been making some pretty good progress with a fork of your parser that I've converted to be based on Span<T>. As a result, it only runs on .NET Core 2.1 or better, but I'm seeing some great results so far.

https://gist.github.com/jtmueller/4e6ab27a3fe82c97e0f315c99123c494

**Comment by bytefish** [comment]
@jtmueller Very impressive work! Feel free to make a Pull Request, when you feel comfortable. 😃

**Comment by bytefish** [comment]
@jtmueller First of all: I added you as a collaborator to this repository, so you should be able to Push to this repository.

But honestly I think it is better to directly do a hard fork to .NET Core, that reflects the library is .NET Core only. The API changes are too large to integrate, it will be a Breaking Change anyway. The Span classes won't be NetStandard 1.3 for some time and I also don't want to maintain two different code bases in case of an error. 

I want to leave the TinyCsvParser 2.0 as it is, because it is stable and people can continue using NuGet for both the .NET Framework and .NET Core version. So let's fork it! 

Do you have any idea for a name of the .NET Core version? "TinyCsvParserDotNetCore" is too long to sound cool... "TinyCsvParserCore"? I am totally open to suggestions!

Please feel free to create the repository with your GitHub profile once we have a name and maybe add me as a collaborator, so we can both work on it.

**Comment by jtmueller** [comment]
I agree, a fork is probably best at this time. Maybe CoreCsvParser or SpanCsvParser? TinyCsvCore? TinyCsvSpan? I'll have to think about it.

Also, I've not turned a fork into its own thing before. Is it best to create a new repository and copy in the code, or would it be better to rename my fork and update the readme/namespaces?

**Comment by bytefish** [comment]
I think CoreCsvParser sounds good and it is not taken on NuGet. So we could use the name once the library is ready for release. What do you think? Let's use it! ✌️

I think the best way to go ahead is to simply create a fresh repository and copy and paste the files into it. There we can adjust the namespaces to "CoreCsvParser". Do you want to create the repository or should I do it? I just don't want to copy and paste your work into a new repository of mine, that wouldn't feel right, because it is your work.

We could also create an organization in GitHub and create a repository there. But that would just complicate things, because then we would need to find another name. 😂

**Comment by jtmueller** [comment]
Sounds good to me. I'll go ahead and create the repository in the next couple of days, if that's okay, since I have a couple of branches to bring in (I'll make my current "core-span" branch the master, and keep the pipelines branch). I'll add you to the repository with as much access as it lets me.

You might want to consider merging the BenchmarkDotNet code from the master branch of my fork into TinyCsvParser - it's more thorough than using unit tests for such things, and provides a good way to compare between the libraries.
