### ISSUE TITLE
Unable to compile latest master

### ISSUE THREAD

**Issue by Krakean** [bytefish/TinyCsvParser#49]
1>GameImpl_TinyCsvParser\Source\Mapping\CsvMapping.cs(62,91,62,96): error CS0104: 'Range' is an ambiguous reference between 'TinyCsvParser.System.Range' and 'System.Range'
1>GameImpl_TinyCsvParser\Source\Mapping\CsvMapping.cs(67,91,67,96): error CS0104: 'Range' is an ambiguous reference between 'TinyCsvParser.System.Range' and 'System.Range'
1>GameImpl_TinyCsvParser\Source\Mapping\CsvMapping.cs(102,52,102,57): error CS0104: 'Range' is an ambiguous reference between 'TinyCsvParser.System.Range' and 'System.Range'
1>GameImpl_TinyCsvParser\Source\Mapping\CsvMapping.cs(31,20,31,25): error CS0104: 'Range' is an ambiguous reference between 'TinyCsvParser.System.Range' and 'System.Range'

VS 2019, .NET Core 3.0

**Comment by bytefish** [comment]
That's because I decided to add a Range feature to the library, so you can also map arrays. I want to take advantadge of the System.Range Data Type. But it's only available from .netstandard 2.1 as far as I can tell. 😢 I will add conditional compilation flags, so it resolves the correct type depending on the target framework. 😓

**Comment by bytefish** [comment]
Fixed! 👍
